{{- if .Values.secrets }}
{{- $labels := include "generic.labels" $ }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{- range .items }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
{{- end }}
{{- end }}
